openapi: 3.0.1
info:
  title: 
  description: 
  version: 1.0.0
servers:
  - url: "http://localhost:8290/context_here"
paths:
  /:
    get:
      responses:
        default:
          description: Default response
